/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packages;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prasad Shinde
 */
public class IssueFrame extends javax.swing.JFrame {

    /**
     * Creates new form IssueFrame
     */
    public IssueFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        issuePanel = new javax.swing.JPanel();
        lblissuehead = new javax.swing.JLabel();
        lblissuesubhead = new javax.swing.JLabel();
        issuereturnPanel = new javax.swing.JTabbedPane();
        issurTpanel = new javax.swing.JPanel();
        lblstudent = new javax.swing.JLabel();
        txtstudent = new javax.swing.JTextField();
        lblbook = new javax.swing.JLabel();
        txtbook = new javax.swing.JTextField();
        btncheckinfo = new javax.swing.JButton();
        lblstudentinfo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentinfotable = new javax.swing.JTable();
        lblenterissue = new javax.swing.JLabel();
        issuedate = new com.toedter.calendar.JDateChooser();
        lblenterreturn = new javax.swing.JLabel();
        returndate = new com.toedter.calendar.JDateChooser();
        btnissue = new javax.swing.JButton();
        returnTpanel = new javax.swing.JPanel();
        lblstudentreturn = new javax.swing.JLabel();
        txtstudentreturn = new javax.swing.JTextField();
        btnsearchreturn = new javax.swing.JButton();
        lblstudentinforeturn = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        studentinforeturntable = new javax.swing.JTable();
        btnreturn = new javax.swing.JButton();
        btntrackhome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        issuePanel.setPreferredSize(new java.awt.Dimension(750, 443));

        lblissuehead.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblissuehead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblissuehead.setText("Collage Library Department");

        lblissuesubhead.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblissuesubhead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblissuesubhead.setText("Issue/Return Book");

        lblstudent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblstudent.setText("Student Id:");

        txtstudent.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lblbook.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblbook.setText("Book Id:");

        txtbook.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btncheckinfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncheckinfo.setText("CHECK");
        btncheckinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckinfoActionPerformed(evt);
            }
        });

        lblstudentinfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblstudentinfo.setText("Student info:");

        studentinfotable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book id", "Issue data", "Return date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentinfotable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentinfotable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        studentinfotable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(studentinfotable);

        lblenterissue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblenterissue.setText("Issue Date");

        issuedate.setDateFormatString("default");

        lblenterreturn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblenterreturn.setText("Return Date");

        returndate.setDateFormatString("default");

        btnissue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnissue.setText("ISSUE");
        btnissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout issurTpanelLayout = new javax.swing.GroupLayout(issurTpanel);
        issurTpanel.setLayout(issurTpanelLayout);
        issurTpanelLayout.setHorizontalGroup(
            issurTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issurTpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(issurTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(issurTpanelLayout.createSequentialGroup()
                        .addGroup(issurTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(issurTpanelLayout.createSequentialGroup()
                                .addComponent(lblstudent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btncheckinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(issurTpanelLayout.createSequentialGroup()
                        .addGroup(issurTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnissue, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(issurTpanelLayout.createSequentialGroup()
                                .addComponent(lblbook)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbook, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblenterissue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblenterreturn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(returndate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, issurTpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblstudentinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        issurTpanelLayout.setVerticalGroup(
            issurTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issurTpanelLayout.createSequentialGroup()
                .addComponent(lblstudentinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(issurTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(issurTpanelLayout.createSequentialGroup()
                        .addGroup(issurTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtstudent)
                            .addComponent(lblstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(btncheckinfo)))
                .addGap(40, 40, 40)
                .addGroup(issurTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(issurTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(issurTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblbook, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblenterissue))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, issurTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(issurTpanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(returndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblenterreturn)))
                    .addGroup(issurTpanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(btnissue)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        issurTpanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblbook, lblenterissue});

        issurTpanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {issuedate, returndate, txtbook});

        issuereturnPanel.addTab("ISSUE", issurTpanel);

        lblstudentreturn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblstudentreturn.setText("Student Id:");

        txtstudentreturn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnsearchreturn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsearchreturn.setText("Search");
        btnsearchreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchreturnActionPerformed(evt);
            }
        });

        lblstudentinforeturn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblstudentinforeturn.setText("Student info:");

        studentinforeturntable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book id", "Issue data", "Return date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentinforeturntable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentinforeturntable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        studentinforeturntable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(studentinforeturntable);

        btnreturn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnreturn.setText("Return");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout returnTpanelLayout = new javax.swing.GroupLayout(returnTpanel);
        returnTpanel.setLayout(returnTpanelLayout);
        returnTpanelLayout.setHorizontalGroup(
            returnTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnTpanelLayout.createSequentialGroup()
                .addGroup(returnTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnTpanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblstudentreturn)
                        .addGap(26, 26, 26)
                        .addComponent(txtstudentreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnsearchreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(returnTpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblstudentinforeturn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(returnTpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(returnTpanelLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        returnTpanelLayout.setVerticalGroup(
            returnTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnTpanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(returnTpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsearchreturn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(txtstudentreturn)
                    .addComponent(lblstudentreturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblstudentinforeturn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        issuereturnPanel.addTab("RETURN", returnTpanel);

        btntrackhome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntrackhome.setText("HOME");
        btntrackhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrackhomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout issuePanelLayout = new javax.swing.GroupLayout(issuePanel);
        issuePanel.setLayout(issuePanelLayout);
        issuePanelLayout.setHorizontalGroup(
            issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issuePanelLayout.createSequentialGroup()
                .addGroup(issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(issuePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(issuereturnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(issuePanelLayout.createSequentialGroup()
                        .addGroup(issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(issuePanelLayout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(lblissuesubhead, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(issuePanelLayout.createSequentialGroup()
                                .addComponent(btntrackhome)
                                .addGap(35, 35, 35)
                                .addComponent(lblissuehead, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        issuePanelLayout.setVerticalGroup(
            issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issuePanelLayout.createSequentialGroup()
                .addGroup(issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblissuehead, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntrackhome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblissuesubhead, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(issuereturnPanel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(issuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(issuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncheckinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckinfoActionPerformed
        try 
        {
            DefaultTableModel tbl=(DefaultTableModel)studentinfotable.getModel();
            tbl.setRowCount(0);
            String id=txtstudent.getText();
            lblstudentinfo.setText("Student info:"+id);
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","Prasadshinde@93");
            Statement st=con.createStatement();
            String str="select* from student where student_id='"+id+"'";
            
            ResultSet rst=st.executeQuery(str);
            while(rst.next())
            {
                String book_id=rst.getString("book_id");
                Date issue=rst.getDate("issue_date");
                Date returndate=rst.getDate("return_date");
                String status=rst.getString("status");
                Object tbdata[]={book_id,issue,returndate,status};
                DefaultTableModel tblModel=(DefaultTableModel)studentinfotable.getModel();
                tblModel.addRow(tbdata);
            }
            con.close();
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Error:"+e);
        }
    }//GEN-LAST:event_btncheckinfoActionPerformed

    private void btnissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissueActionPerformed
        try 
        {
            String studentid=txtstudent.getText();
            lblstudentinfo.setText("Student info:"+studentid);
            int bookid=Integer.parseInt(txtbook.getText());
            String string="select*from total_books";
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","Prasadshinde@93");
            Statement st=con.createStatement();
            ResultSet rst=st.executeQuery(string);
            int flag=0;
            while(rst.next())
            {
                if(bookid==rst.getInt("book_id"))
                {
                    flag=1;
                }
            }
            if(flag==0)
            {
                JOptionPane.showMessageDialog(this, "Wrong Book id");
                return;
            }
            
            Date issue=new Date(issuedate.getDate().getTime());
            Date returnd=new Date(returndate.getDate().getTime());
            string="select no_of_copies from total_books where book_id="+bookid;
            rst=st.executeQuery(string);
            int no;
            if(rst.first())
            {
                no=rst.getInt("no_of_copies");
                if(no==0)
                {
                    JOptionPane.showMessageDialog(this,"Book not available");
                    return;
                }
            }else
            {
                return;
            }
            String str="INSERT into student values('"+studentid+"',"+bookid+",'"+issue+"','"+returnd+"','not return')";
            st.executeUpdate(str);
            JOptionPane.showMessageDialog(this,"Book issued successfully");
            String str1="select* from student where student_id='"+studentid+"'";
            DefaultTableModel tbl=(DefaultTableModel)studentinfotable.getModel();
            tbl.setRowCount(0);
            rst=st.executeQuery(str1);
            while(rst.next())
            {
                String book_id=rst.getString("book_id");
                issue=rst.getDate("issue_date");
                returnd=rst.getDate("return_date");
                String status=rst.getString("status");
                Object tbdata[]={book_id,issue,returnd,status};
                DefaultTableModel tblModel=(DefaultTableModel)studentinfotable.getModel();
                tblModel.addRow(tbdata);
            }
            txtbook.setText("");
            txtstudent.setText("");
            issuedate.setDate(null);
            returndate.setDate(null);
            no--;
            str="update total_books set no_of_copies="+no+" where book_id="+bookid;
            st.executeUpdate(str);
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Incomplete Information="+e);
        }
    }//GEN-LAST:event_btnissueActionPerformed

    private void btnsearchreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchreturnActionPerformed
        try 
        {
            DefaultTableModel tbl=(DefaultTableModel)studentinforeturntable.getModel();
            tbl.setRowCount(0);
            String id=txtstudentreturn.getText();
            lblstudentinforeturn.setText("Student info:"+id);
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","Prasadshinde@93");
            Statement st=con.createStatement();
            String str="select* from student where student_id='"+id+"'";
            
            ResultSet rst=st.executeQuery(str);
            while(rst.next())
            {
                String book_id=rst.getString("book_id");
                Date issue=rst.getDate("issue_date");
                Date returndate=rst.getDate("return_date");
                String status=rst.getString("status");
                Object tbdata[]={book_id,issue,returndate,status};
                DefaultTableModel tblModel=(DefaultTableModel)studentinforeturntable.getModel();
                tblModel.addRow(tbdata);
            }
            con.close();
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Error:"+e);
        }
    }//GEN-LAST:event_btnsearchreturnActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        try 
        {
            int a=studentinforeturntable.getSelectedRow();
            String status=(String)studentinforeturntable.getValueAt(a,3);
            if(status.equals("return"))
            {
                JOptionPane.showMessageDialog(this, "Already return");
                return;
            }
            if(studentinforeturntable.isRowSelected(a))
            {
                String student_id=txtstudentreturn.getText();
                String book_id=(String)studentinforeturntable.getValueAt(a,0);
                String str="UPDATE student SET status='return' WHERE student_id='"+student_id+"'and book_id='"+Integer.parseInt(book_id)+"'";
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","Prasadshinde@93");
                Statement st=con.createStatement();
                st.executeUpdate(str);
                JOptionPane.showMessageDialog(this, "Return Successfully");
                DefaultTableModel tbl=(DefaultTableModel)studentinforeturntable.getModel();
                tbl.setRowCount(0);
                String string="select no_of_copies from total_books where book_id="+book_id;
                ResultSet rst=st.executeQuery(string);
                int no;
                if(rst.first())
                {
                    no=rst.getInt("no_of_copies");
                    no++;
                    str="update total_books set no_of_copies="+no+" where book_id="+book_id;
                    st.executeUpdate(str);
                }
            }
        } 
        catch (Exception e) 
        {
            
        }
    }//GEN-LAST:event_btnreturnActionPerformed

    private void btntrackhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrackhomeActionPerformed
        mainFrame obj=new mainFrame();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btntrackhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckinfo;
    private javax.swing.JButton btnissue;
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton btnsearchreturn;
    private javax.swing.JButton btntrackhome;
    private javax.swing.JPanel issuePanel;
    private com.toedter.calendar.JDateChooser issuedate;
    private javax.swing.JTabbedPane issuereturnPanel;
    private javax.swing.JPanel issurTpanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblbook;
    private javax.swing.JLabel lblenterissue;
    private javax.swing.JLabel lblenterreturn;
    private javax.swing.JLabel lblissuehead;
    private javax.swing.JLabel lblissuesubhead;
    private javax.swing.JLabel lblstudent;
    private javax.swing.JLabel lblstudentinfo;
    private javax.swing.JLabel lblstudentinforeturn;
    private javax.swing.JLabel lblstudentreturn;
    private javax.swing.JPanel returnTpanel;
    private com.toedter.calendar.JDateChooser returndate;
    private javax.swing.JTable studentinforeturntable;
    private javax.swing.JTable studentinfotable;
    private javax.swing.JTextField txtbook;
    private javax.swing.JTextField txtstudent;
    private javax.swing.JTextField txtstudentreturn;
    // End of variables declaration//GEN-END:variables
}
