/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packages;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prasad Shinde
 */
public class Trackframe extends javax.swing.JFrame {

    public Trackframe() 
    {
        initComponents();
          try 
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "Prasadshinde@93");
            Statement st=con.createStatement();
            ResultSet rst=st.executeQuery("select*from total_books");
            while(rst.next())
            {
                String book_id=rst.getString("book_id");
                String book_name=rst.getString("book_name");
                String author=rst.getString("author");
                String publisher=rst.getString("publisher");
                String isbn=rst.getString("isbn");
                String length=rst.getString("length");
                String category_id=rst.getString("category_id");
                String no_of_copies=rst.getString("no_of_copies");
                
                
                String tbdata[]={book_id,book_name,author,publisher,isbn,length,category_id,no_of_copies};
                DefaultTableModel tblModel=(DefaultTableModel)totalTable.getModel();
                tblModel.addRow(tbdata);
            }
            con.close();
        } 
        catch (Exception e) 
        {
            System.err.println("Error"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trackPanel = new javax.swing.JPanel();
        lbltrackhead = new javax.swing.JLabel();
        lblhead = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        totalTable = new javax.swing.JTable();
        btntrackhome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbltrackhead.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbltrackhead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltrackhead.setText("Collage Library Department");

        lblhead.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblhead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        totalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book id", "Book Name", "Author", "Publisher", "ISBN", "Length", "Category", "Total Copies"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(totalTable);

        btntrackhome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntrackhome.setText("HOME");
        btntrackhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrackhomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trackPanelLayout = new javax.swing.GroupLayout(trackPanel);
        trackPanel.setLayout(trackPanelLayout);
        trackPanelLayout.setHorizontalGroup(
            trackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trackPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lbltrackhead, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(trackPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(trackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trackPanelLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(lblhead, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(btntrackhome)
        );
        trackPanelLayout.setVerticalGroup(
            trackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trackPanelLayout.createSequentialGroup()
                .addComponent(btntrackhome)
                .addGap(22, 22, 22)
                .addComponent(lbltrackhead, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(trackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trackPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblhead, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btntrackhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrackhomeActionPerformed
        mainFrame obj=new mainFrame();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btntrackhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trackframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trackframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trackframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trackframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trackframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntrackhome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblhead;
    private javax.swing.JLabel lbltrackhead;
    private javax.swing.JTable totalTable;
    private javax.swing.JPanel trackPanel;
    // End of variables declaration//GEN-END:variables
}
